#!/bin/sh
set -e # stop if we encounter an error

svn update
make -j3

# Update a timestamp so we can check whether each mirror is
# up to date.
[ -d project/trace ] || mkdir -p project/trace
date -u > project/trace/www.torproject.org

# don't copy over stuff with permissions that make it useless
chmod a+r * -R
rsync --exclude .svn --exclude .deps --exclude svn --exclude dist --exclude releases --exclude torbutton-current.xpi -Prvz --delete . vescum:/srv/www-master.torproject.org/htdocs
ssh vescum chmod g+w -R /srv/www-master.torproject.org/htdocs

echo "Forcing mirror update"
ssh vescum '/var/lib/mirror-tor/trigger-sync'

