#!/bin/sh
set -e # stop if we encounter an error

# pull the latest changes
svn update

# clean up the working directory
make clean

# actually build the site
make -j3

# don't copy over stuff with permissions that make it useless
chmod -R a+r *
rsync --exclude .svn --exclude .deps --exclude svn --exclude dist --exclude releases --exclude torbutton-current.xpi --exclude project -Prvz --delete . vescum:/srv/www-master.torproject.org/htdocs

echo "Forcing mirror update"
ssh vescum '/home/mirroradm/bin/trigger-mirrors'
ssh vescum chmod g+w -R /srv/www-master.torproject.org/htdocs
